Don't apply upstream patches in panda patch
Changes:
* Only apply PandaSpigot patches in "patch" command.
* Removed previous "install" command.
* Renamed "setup" command to "install".
* Added "setup" command to do what "patch" previously did.

diff --git a/panda b/panda
--- a/panda
+++ b/panda
@@ -45,6 +45,13 @@ case "$1" in
         scripts/rebuildPatches.sh "$basedir" "nofilter" || exit 1
     ) || failed=1
     ;;
+    "setup")
+    (
+        set -e
+        cd "$basedir"
+        scripts/build.sh "$basedir" "--setup" || exit 1
+    ) || failed=1
+    ;;
     "p" | "patch")
     (
         set -e
@@ -57,15 +64,6 @@ case "$1" in
         set -e
         cd "$basedir"
         scripts/build.sh "$basedir" "--jar" || exit 1
-    ) || failed=1
-    ;;
-    "i" | "install")
-    (
-        set -e
-        cd "$basedir"
-        scripts/build.sh "$basedir" || exit 1
-        ./gradlew publishToMavenLocal || exit 1
-        echo "PandaSpigot jar successfully built and installed to local repo"
     ) || failed=1
     ;;
     "pc" | "paperclip")
@@ -151,7 +149,7 @@ case "$1" in
             ;;
         esac
     ;;
-    "setup")
+    "install")
         if [[ -f "$RCPATH" ]] ; then
             NAME="panda"
             if [[ ! -z "${2+x}" ]] ; then
@@ -161,23 +159,23 @@ case "$1" in
             alias "$NAME=. $SOURCE"
             echo "You can now just type '$NAME' at any time to access the panda tool."
         else
-          echo "We were unable to setup the panda build tool alias: $RCPATH is missing"
+          echo "We were unable to install the panda build tool alias: $RCPATH is missing"
         fi
     ;;
     *)
         echo "PandaSpigot build tool command. This provides a variety of commands to build and manage the PandaSpigot build"
         echo "environment. For all of the functionality of this command to be available, you must first run the"
-        echo "'setup' command. View below for details. For essential building and patching, you do not need to do the setup."
+        echo "'install' command. View below for details. For essential building and patching, you do not need to do the install."
         echo ""
         echo " Normal commands:"
         echo "  * rb, rebuild         | Rebuild patches, can be called from anywhere."
+        echo "  * setup               | Remap, decompile, and patch Minecraft. Can be run from anywhere."
         echo "  * p, patch            | Apply all patches to the project without building it. Can be run from anywhere."
         echo "  * j, jar              | Apply all patches and build the project, paperclip.jar will be output. Can be run from anywhere."
-        echo "  * i, install          | Build and install PandaSpigot into the local repo. Can be run from anywhere."
         echo "  * c, clean            | Removes all generated files, PandaSpigot-API, PandaSpigot-Server, and work."
         echo "  * con, continue       | Shortcut command for running git am --continue, or git rebase --continue."
         echo ""
-        echo " These commands require the setup command before use:"
+        echo " These commands require the install command before use:"
         echo "  * r, root             | Change directory to the root of the project."
         echo "  * a. api              | Move to the PandaSpigot-API directory."
         echo "  * s, server           | Move to the PandaSpigot-Server directory."
@@ -185,12 +183,12 @@ case "$1" in
         echo "                        | respectively to edit the correct project. Use the argument \"continue\" after"
         echo "                        | the changes have been made to finish and rebuild patches. Can be called from anywhere."
         echo ""
-        echo "  * setup               | Add an alias to $RCPATH to allow full functionality of this script. Run as:"
-        echo "                        |     . ./panda setup"
+        echo "  * install             | Add an alias to $RCPATH to allow full functionality of this script. Run as:"
+        echo "                        |     . ./panda install"
         echo "                        | After you run this command you'll be able to just run 'panda' from anywhere."
         echo "                        | The default name for the resulting alias is 'panda', you can give an argument to override"
         echo "                        | this default, such as:"
-        echo "                        |     . ./panda setup example"
+        echo "                        |     . ./panda install example"
         echo "                        | Which will allow you to run 'example' instead."
     ;;
 esac
